### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by panosl** [dschoon/react-waves#1]
Trying to execute: `npm install --save react-waves` fails with the log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'react-waves' ]
2 info using npm@6.5.0
3 info using node@v11.7.0
4 verbose npm-session 5dd4b74b2c290129
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/react-waves 869ms
8 silly fetchPackageMetaData error for react-waves@latest 404 Not Found: react-waves@latest
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 2951ms
11 verbose stack Error: 404 Not Found: react-waves@latest
11 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
11 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
11 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
11 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
11 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at processImmediate (timers.js:632:19)
12 verbose cwd /Users/panosl/Code/breathresearch/afpgui
13 verbose Darwin 16.7.0
14 verbose argv "/usr/local/Cellar/node/11.7.0/bin/node" "/usr/local/bin/npm" "install" "--save" "react-waves"
15 verbose node v11.7.0
16 verbose npm  v6.5.0
17 error code E404
18 error 404 Not Found: react-waves@latest
19 verbose exit [ 1, true ]
```

It only works if I do: `npm i @dschoon/react-waves --save`

**Comment by aarondack** [comment]
Hi @panosl,

The reason for this is because `react-waves` is taken in npm so Dan had to publish it under `@dschoon/react-waves`. I'll update the `README`, thanks.

**Comment by dschoon** [comment]
Here's the PR to correct the README: https://github.com/dschoon/react-waves/pull/2
